services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookbazar_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=2026!Spring
    ports:
      - "1433:1433"

  app:
    build: .
    container_name: bookbazar_app
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BookBazarDb;User=sa;Password=2026!Spring;TrustServerCertificate=True