// <auto-generated />
using BookBazar.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBazar.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260406194258_IntialDBSetup")]
    partial class IntialDBSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBazar.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Self Help"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("BookBazar.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Thomas Erikson",
                            CategoryId = 1,
                            Description = "A popular self-help book about understanding personality types and improving communication with different kinds of people.",
                            ISBN = "9781250179944",
                            ImageUrl = "/images/products/books/surrounded-by-idiots.jpg",
                            ListPrice = 18.0,
                            Price = 16.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "Surrounded by Idiots"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Michelle Obama",
                            CategoryId = 2,
                            Description = "A memoir by Michelle Obama about her life, family, values, and journey from childhood to the White House.",
                            ISBN = "9781524763138",
                            ImageUrl = "/images/products/books/becoming.jpg",
                            ListPrice = 20.0,
                            Price = 18.0,
                            Price100 = 14.0,
                            Price50 = 16.0,
                            Title = "Becoming"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Héctor García and Francesc Miralles",
                            CategoryId = 1,
                            Description = "A self-help book exploring the Japanese idea of ikigai, or finding purpose, meaning, and joy in life.",
                            ISBN = "9780143130727",
                            ImageUrl = "/images/products/books/ikigai.jpg",
                            ListPrice = 17.0,
                            Price = 15.0,
                            Price100 = 11.0,
                            Price50 = 13.0,
                            Title = "Ikigai"
                        },
                        new
                        {
                            Id = 4,
                            Author = "James Clear",
                            CategoryId = 1,
                            Description = "A bestselling self-improvement book about building good habits, breaking bad ones, and making small changes that produce big results.",
                            ISBN = "9780735211292",
                            ImageUrl = "/images/products/books/atomic-habits.jpg",
                            ListPrice = 20.0,
                            Price = 18.0,
                            Price100 = 14.0,
                            Price50 = 16.0,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Virginia Evans",
                            CategoryId = 3,
                            Description = "A literary fiction novel centered on relationships, emotional depth, and human connection.",
                            ISBN = "9780593654477",
                            ImageUrl = "/images/products/books/the-correspondent.jpg",
                            ListPrice = 19.0,
                            Price = 17.0,
                            Price100 = 13.0,
                            Price50 = 15.0,
                            Title = "The Correspondent"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Allen Levi",
                            CategoryId = 3,
                            Description = "A reflective and emotional novel about life, memory, and meaningful human experiences.",
                            ISBN = "9781637632697",
                            ImageUrl = "/images/products/books/theo-of-golden.jpg",
                            ListPrice = 18.0,
                            Price = 16.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "Theo of Golden"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Joseph Murphy",
                            CategoryId = 1,
                            Description = "A motivational self-help classic focused on confidence, belief, and the power of the mind.",
                            ISBN = "9789355994653",
                            ImageUrl = "/images/products/books/believe-in-yourself.jpg",
                            ListPrice = 15.0,
                            Price = 13.0,
                            Price100 = 9.0,
                            Price50 = 11.0,
                            Title = "Believe in Yourself"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Anthony Doerr",
                            CategoryId = 4,
                            Description = "A bestselling historical fiction novel set during World War II, following the lives of a blind French girl and a German boy.",
                            ISBN = "9781501173219",
                            ImageUrl = "/images/products/books/all-the-light-we-cannot-see.jpg",
                            ListPrice = 19.0,
                            Price = 17.0,
                            Price100 = 13.0,
                            Price50 = 15.0,
                            Title = "All the Light We Cannot See"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Stacy Willingham",
                            CategoryId = 5,
                            Description = "A psychological thriller with suspense, secrets, and disturbing twists tied to crimes from the past.",
                            ISBN = "9781250803825",
                            ImageUrl = "/images/products/books/a-flicker-in-the-dark.jpg",
                            ListPrice = 18.0,
                            Price = 16.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "A Flicker in the Dark"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Shubham Kumar Singh",
                            CategoryId = 1,
                            Description = "A motivational and mindset-focused self-help book about mastering thoughts and shaping your life through positive thinking.",
                            ISBN = "9780143475279",
                            ImageUrl = "/images/products/books/you-become-what-you-think.jpg",
                            ListPrice = 16.0,
                            Price = 14.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "You Become What You Think"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Morgan Housel",
                            CategoryId = 1,
                            Description = "A personal finance and self-development book explaining how behavior, emotions, and decision-making shape financial success.",
                            ISBN = "9780857197689",
                            ImageUrl = "/images/products/books/the-psychology-of-money.jpg",
                            ListPrice = 18.0,
                            Price = 16.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "The Psychology of Money"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Rebecca Yarros",
                            CategoryId = 6,
                            Description = "A fantasy novel filled with dragons, war college training, danger, and romance.",
                            ISBN = "9781649374042",
                            ImageUrl = "/images/products/books/fourth-wing.jpg",
                            ListPrice = 22.0,
                            Price = 20.0,
                            Price100 = 16.0,
                            Price50 = 18.0,
                            Title = "Fourth Wing"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Mel Robbins",
                            CategoryId = 1,
                            Description = "A self-help and mindset book focused on letting go of control, reducing stress, and living with more freedom.",
                            ISBN = "9781401971366",
                            ImageUrl = "/images/products/books/the-let-them-theory.jpg",
                            ListPrice = 19.0,
                            Price = 17.0,
                            Price100 = 13.0,
                            Price50 = 15.0,
                            Title = "The Let Them Theory"
                        });
                });

            modelBuilder.Entity("BookBazar.Models.Product", b =>
                {
                    b.HasOne("BookBazar.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
